var THESAURUS = {
	three: ["ACT","BIG","IS","WAS","ADD", "AGE","FOB","BAT", "AGO","HAT","ARMY" ,"AIR","FIRE","CAR","TIE", "ALL", "AND", "ANY", "ARE", "ARM", "ART", "ASK", "YET", "YOU", "ZOO"],
	small: ["MIME","SULKS","FRIZZ","ELKS","FILLS","CAST"],
	medium: ["PORTICO","SIZZLES","UMBRELLA","LINEARLY","IMPOTENT","FLEABAGS","LEARNT","CRYPTIC","ESCAPE","SAUCEPAN","DIPSTICK","WEAVED","WAGGON","NEURONS","PERUSE","GLOBALLY","MANNED"],
	big: ["BLANCMANGE","BESIEGING","SPORTSWEAR","REALIZATION","VIRULENCE","TRAGICALLY","FLOGGINGS","VIBRAPHONE"],
	
};