var THESAURUS = {
	three : [
		'and', 'del', 'for', 'not', 'try',
		'as', 'elif', 'from', 'or', 'while',
		'assert', 'else', 'if', 'pass', 'with',
		'break', 'except', 'in', 'is', 'def',
		'int', 'str', 'abs', 'hex', 'max',
		'min', 'len', 'ord', 'pow', 'set',
		'sum', 'map', 'zip'
	],
	small : [
		'else', 'from', 'import', 'raise', 'yield',
		'class', 'except', 'while', 'lambda', 'global',
		'async', 'await', 'range', 'input', 'print',
		'float', 'tuple', 'dict', 'list', 'super',
		'sorted', 'isinstance', 'format', 'locals', 'zip',
		'bytes', 'slice', 'tuple', 'round', 'input',
		'range', 'str', 'int', 'bool', 'file',
		'break', 'continue', 'def', 'elif', 'exec',
		'finally', 'global', 'nonlocal', 'pass', 'try'
	],
	
	
	medium:[
		'assert', 'except', 'finally', 'continue', 'iterator',
		'classmethod', 'property', 'delattr', 'repr', 'staticmethod',
		'evaluate', 'isalnum', 'hexlify', 'isalpha', 'dir',
		'issubclass', 'eval', 'isdecimal', 'fromhex', 'bin',
		'locals', 'callable', 'chr', 'globals', 'exec',
		'map', 'complex', 'issuper', 'exit', 'math',
		'compile', 'setattr', 'filter', 'staticmethod', 'hasattr',
		'enumerate', 'len', 'isinstance', 'open', 'getattr',
		'int', 'isidentifier', 'ord', 'id', 'print',
		'round', 'staticmethod', 'staticmethod', 'slice', 'iter',
		'zip', 'unicode', 'super', 'range', 'setattr',
		'setattr', 'setattr', 'tuple', 'reduce', 'hash',
		'staticmethod', 'yield', 'staticmethod', 'staticmethod', 'staticmethod'
	],
	
	big: ["PICNICKED","ADMONITIONS","EXCULPATE","HOSPITABLY","VORACIOUS","PUNCTUATION","LUDICROUS","ENORMOUSLY","QUALIFYING","DISLOCATES","KNOCKOUTS","CAMPANILES","BROADSWORDS","DEMONIACAL","GENERALISTS","PARENTHESES","INFANTRYMEN","PHONETICIAN","LABELLING","FORGETTING","SOBRIQUETS","OUTWEIGHING","INTIMATIONS","SPACEWALKS","DEPRESSANT","PARALYZES","COMBATING","GOALPOSTS","SHOEMAKER","HARDCOVER","CHEMICALLY","STRATEGIES","EXUBERANTLY","DAYDREAMS","PLUPERFECT","WEEKNIGHT","GLOSSINESS","SANITARIUMS","ANAESTHESIA","TENDERIZED","ABDOMINAL","PROPAGATE","SOUNDINGS","CHANCELLORS","PRESSURISE","QUIZZICAL","OUTRUNNING","ANGLICISM","REPELLENT","PEDALLING","RIDICULING","AFTERNOON","PALPITATES","PUNGENTLY","SUCCOURED","CASTRATED","GREENGAGES","PRESIDENT","TRELLISES","JUSTIFIED","UNEARTHING","PHYSIOLOGY","PAUNCHIEST","SYNDICATED","ENSLAVEMENT","INNOCENCE","KINGMAKER","FLABBIEST","SHEIKHDOM","FULMINATE","SUBMISSIONS","HESITATIONS","RESERVING","DEFINITELY","PURCHASED","CARAMELISED","ADRENALINE","DRESSIEST","UPSETTING","WICKEDEST","ENTITLEMENT","POPULARLY","INNUENDOS","BILBERRIES","SHORELINE","ATTAINING","DISCOURAGE","MARTINETS","REMOUNTED","NOBLEWOMEN","OMBUDSMEN","CANCEROUS","FARMLANDS","OVERRULING","GRENADIERS","UNDERSIZED","REVEALING","SKITTISHLY","EVANGELISM","REPUDIATED","ANNEALING","POLICYMAKER","BARRACUDA","CASELOADS","PERMANENCY","PATHOGENS","POLITICALLY","MESMERIZES","DISORDERS","MEGASTARS","ADVERSARY","SEAMANSHIP","BIVOUACKING","BANDSTANDS","APPROBATION","COURTSHIP","OPTICIANS","HAIRSTYLE","PROCLAIMS","FLYWEIGHT","FORGATHERED","UNDERCLASS","CAREGIVER","DISAPPEARS","REDCURRANT","MOBILISING","OVERRATES","CORPUSCLES","SYNAGOGUE","BELABORED","DISPARAGING","IRRITATES","INSANITARY","CREATIONIST","CASTRATING","BUTTONHOLES","ARMADILLOS","FRONTBENCH","CHAINSAWS","REHEARSING","FLAKINESS","PRESUMING","HANDCUFFING","FORTIETHS","CHECKLIST","SPECULATE","SUNDERING","REMOVABLE","BUBBLEGUM","CORPOREAL","THRASHING","MOTIVATIONS","DISLOYALTY","DIGNITARIES","DIRECTIONAL","BYSTANDERS","PORTIONING","IMMIGRATION","REALIGNING","RESTORATIVE","CENTENNIALS","SOCIALITE","PSYCHIATRY","STIGMATIZED","YAMMERING","ELECTRICITY","DATELINES","COLOURIZING","PAROCHIAL","STRANGLED","DISQUALIFY","NANOSECOND","REFERABLE","MAJESTIES","RESPONDING","RESONATED","EGGSHELLS","EXCORIATING","INTOLERANT","CATALYZES","TRIUMPHAL","SALIVATED","REPENTING","INQUIRINGLY","IMMORALLY","BANDLEADERS","SCALLYWAGS","EXPECTORATE","TIMESERVERS","REMINDERS","CATALOGUE","TERMINATION","BLANCMANGE","BESIEGING","SPORTSWEAR","REALIZATION","VIRULENCE","TRAGICALLY","FLOGGINGS","VIBRAPHONE"],
	large: ["STRAIGHTENING","DEREGULATING","INEXPRESSIBLY","INTRANSITIVELY","NYMPHOMANIACS","HYSTERECTOMIES","SPECTROSCOPES","COUNTERTENORS","UNFAVOURABLE","WELTERWEIGHT","TECHNOLOGIST","TRACTABILITY","MODERNIZATION","CHECKERBOARDS","STREPTOCOCCAL","REDISTRIBUTES","HOMOEOPATHIC","UNREMITTINGLY","SPEEDOMETERS","PROSELYTIZES","REINSTATEMENT","DECONTAMINATE","ILLEGALITIES","AGRIBUSINESS","NEOCLASSICAL","CHIVALROUSLY","SKITTISHNESS","DISEMBOWELING","REORGANISATION","COLLABORATION","DISASSOCIATES","PERSONALIZED","WHOLEHEARTED","CONCESSIONAIRE","PASTEURIZING","TRANSGRESSED","RHAPSODISING","UNILATERALLY","RESTRUCTURINGS","CHAIRPERSONS","INCREASINGLY","PTERODACTYLS","FASCINATINGLY","PRIZEFIGHTER","EXPLOSIVENESS","ADAPTABILITY","MAGNANIMOUSLY","CRYSTALLIZED","AMATEURISHNESS","EXPANSIONISM","MISREPRESENTED","INDEPENDENTLY","COUNTENANCES","BEATIFICATIONS","SPENDTHRIFTS","CONTRIBUTIONS","EXTERMINATING","ALTERCATIONS","BOWDLERIZING","BLABBERMOUTHS","OUTRAGEOUSLY","REINFORCEMENT","ACQUISITIVENESS","CENTRALIZATION","PRESUMPTIONS","REDUNDANCIES","BLINDFOLDING","SEISMOLOGICAL","UNDERCLOTHING","INDEMNIFYING","COUNTERPANES","WHIPPOORWILL","NONCOMBATANT","WEIGHBRIDGES","BEATIFICATION","INDIVIDUALIZED","RIDICULOUSLY","EXTINGUISHERS","INTRANSITIVES","AUTHORITATIVELY","DISQUALIFIES","CAMOUFLAGING","SUBJECTIVELY","DISINGENUOUSLY","EMBARRASSMENT","PREDETERMINED","SPIRITUALITY","EXTRAORDINARILY","HOUSEMASTERS","DISPOSSESSES","CATASTROPHES","APATHETICALLY","INTERLOCUTOR","ILLEGITIMATELY","AUTHENTICALLY","SOLICITATIONS","ACCEPTABILITY","NYMPHOMANIAC","CONCERTINAED","CONTINUANCES","STRETCHMARKS","OMNIPRESENCE","PHYSIOTHERAPIST","RECAPITALIZED","PORTENTOUSNESS","SCRIPTWRITER","VISCOUNTESSES","INSENSITIVITY","BARNSTORMING","NATURALIZING","RECONSTRUCTS","GUILLOTINING","DIVERSIFICATION","INVINCIBILITY","COMMONWEALTH","ETHNOCENTRIC","DEFICIENCIES","LONGSHOREMEN","COUNTERCULTURES","EXPRESSIVENESS","MANIPULATIONS","INTERPOLATES","STABILISATION","OVERINDULGES","PERFECTIONISTS","FORCEFULNESS","ACADEMICALLY","UNACCOMPANIED","REPRESSIVENESS","UNDERSTANDABLY","CONGRATULATING","CANTANKEROUS","DESTABILIZING","LEGITIMIZING","LEATHERNECKS","INFILTRATION","SENTIMENTALISED","CUMULATIVELY","FORBIDDINGLY","ENCRUSTATION","COLLABORATING","OUTDISTANCED","INCORPORATING","QUANTITATIVELY","APPENDECTOMY","MICROCOMPUTER","INDETERMINACY","REMINISCENCE","DEMORALISATION","DEMILITARISES","DETERMINISTIC","INTERCONNECTING","INGRATIATING","PARTISANSHIP","YELLOWHAMMERS","PRODUCTIVELY","DISCONTINUITIES","DISAPPOINTING","WHITEWASHING","CONGENITALLY","HEARTRENDING","TRANSMOGRIFY","CLIMATOLOGIST","OBSERVATIONS","PORNOGRAPHER","SOCIOLOGICALLY","CLASSIFIABLE","EXTERNALISES","EMASCULATION","CALCULATIONS","UNINTENTIONAL","DESPONDENTLY","CHARACTERISE","DISTRESSINGLY","RENDEZVOUSING","BLABBERMOUTH","DISSIMILARITIES","CONDITIONALLY","RECONSTRUCTIONS","DIAMETRICALLY","READDRESSING","HOUSEKEEPING","CONTINUATION","CAPABILITIES","CONTENTIOUSLY","INTERCEPTING","OXYACETYLENE","STOCKBROKING","APPERTAINING","ENCOURAGEMENTS","RECONNOITRES","GUARDIANSHIP","ACQUAINTANCE","SUMMERHOUSES","RESEMBLANCES","EGOCENTRICALLY","PROBABILITIES","BREATHALYZING","SCOREKEEPERS","MILLIONAIRESS"]
};
